### ISSUE TITLE
Updating capabilities

### ISSUE THREAD

**Issue by KuraiKokoro** [RocketRobz/TWiLightMenu-Updater#2]
At the moment there's no way to auto-update DSIMenu++. Is DSIMenu++-Launcher the proper place to implement this?

**Comment by Robz8** [comment]
Yes.

**Comment by d0k3** [comment]
Seconding that request, too. Good to see people already did my feature requests :^)

**Comment by d0k3** [comment]
@Robz8 - I really don't want to be that guy (the nagging type), but with a software updating as often as DSiMenu++ does, there's real big demand for an autoupdater.

There is also another issue open here, coming from a guy who already tried his hands on that. 
https://github.com/Robz8/DSiMenuPlusPlus-Launcher/issues/6
Maybe it wouldn't even be that much work to get that working?

In the meantime (i.e. if the auotupdater turns out to be more complicated), you could also look into @LiquidFenrir's [MultiUpdater](https://github.com/LiquidFenrir/MultiUpdater) (that's pretty much the swiss army knife of autoupdaters) and provide intructions to your users to update via that.

**Comment by Robz8** [comment]
I've been focusing on DSiMenu++ itself, that auto-updating was a low priority. :P

**Comment by d0k3** [comment]
Yeah, I've seen that, and it's great to see DSiMenu++ progressing as fast as it does.

Still making the case for an autoupdater (soon) here - implementing that would mean more people actually using the most recent version, which in turn would mean more useful feedback for you and bugs getting discovered more quickly.

I myself, for example, am using an outdated version right now, simply because updating DSiMenu++ via FTP or an SD card reader is a hassle. I do update from time to time, but with an autoupdater I'd always use the most recent version.

Maybe you could reuse some TWLoader code? I'd even offer my help, but I'm not really a userland guy, so I wouldn't actually be of much help.

**Comment by Robz8** [comment]
Yeah, that's the plan.

**Comment by KuraiKokoro** [comment]
I have to admit, I've not updated in a while as well. The ability to update before launching w/ TWloader made things beyond convenient.

**Comment by RocketRobz** [comment]
@d0k3 fyi, the next version of the launcher will just be an updater for TWiLight Menu++.

**Comment by FlameAlt53** [comment]
this can be closed now

**Comment by KuraiKokoro** [comment]
Thank you for solving this, was a long needed update. 👍
