### ISSUE TITLE
[Feature Request] Skip downloading existing boxart

### ISSUE THREAD

**Issue by JeodC** [RocketRobz/TWiLightMenu-Updater#47]
This is a simple one and is meant for fan translations and/or custom boxarts. Skip downloading if an existing boxart file exists.

**Comment by nabilhoche83** [comment]
It is a very good idea and from my point of view it can be easy (since I am not a developer or programmer) since in the folder where the boxart is stored, they have the names of the title id (own digits to identify a game) and it would be good idea that when detecting a title id has it registered in the memory of the program and if it detects again the game will be able to jump it instead of overwriting it, saving time and memory.
