### ISSUE TITLE
3.1.2 Crashes without a networkconnection 

### ISSUE THREAD

**Issue by J0las** [RocketRobz/TWiLightMenu-Updater#72]
Trying to open the updater with networking disabled crashes the cia after a broken homebrew screen.

Everything behaves as expected with a network and internet connection.

Systeminformation:
Modell: Old 2DS
System Region: EU
System Language: German
OS version 11.10.0-43E
Luma 3DS Version: 9.1

[Files.zip](https://github.com/RocketRobz/TWiLightMenu-Updater/files/3331822/Files.zip)

**Comment by kescherCode** [comment]
@J0las means the part where the second half of the Homebrew logo still shows due to it still being in VRAM.

Basically, crashing right at launch.
## System info

| Info | Value |
|:-----------------------:|:--------------:|
| Model | New 3DS XL (E) |
| System Region | EUR |
| System Language | English |
| Luma version | 9.1 |
| System firmware version | 11.10.0-43E |

## Additional dump
[crash_dump_00000000.dmp.gz](https://github.com/RocketRobz/TWiLightMenu-Updater/files/3332009/crash_dump_00000000.dmp.gz)

**Comment by SuperSaiyajinVoltZ** [comment]
This is a Github API Issue, the latest Release somehow also checks for Updates, even if there is no Connection activated. The latest Commits should Have a Check, if WiFi is enabled, and if the WiFi is not enabled, it doesn't check for Updates.

**Comment by eku** [comment]
@SuperSaiyajinVoltZ  The current nighly build also crashes immediately when the WLAN connection is turned off.

**Comment by RocketRobz** [comment]
Fixed in v4.2.0.
